"""ideapress.domain.audit — findings, and the rule that an auditor cannot change anything.

Workflows §1, rule 2: *auditors report; the writer repairs.* The stage that produced text never
grades it, and the stage that grades it never edits it.

That rule is enforced by **the return type**, not by discipline: an audit stage returns
:class:`AuditReport`, which holds findings and carries no text at all. There is nowhere for revised
content to travel through, so an auditor that wanted to rewrite the unit could not express it. A
test asserts the type has no content field, because a future field called ``suggested_text`` is
exactly how this rule would quietly stop being true.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Final, Literal

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = [
    "SEVERITY_ORDER",
    "AuditFinding",
    "AuditReport",
    "Severity",
    "finding_delta",
    "weighted_score",
]

Severity = Literal["critical", "major", "minor", "nit"]

SEVERITY_ORDER: Final[tuple[Severity, ...]] = ("critical", "major", "minor", "nit")
"""Worst first. The order is data so a report, a UI and a threshold all sort the same way."""

_SEVERITY_WEIGHT: Final[dict[str, float]] = {
    "critical": 1.0,
    "major": 0.5,
    "minor": 0.15,
    "nit": 0.05,
}
"""What each severity costs the audit score.

These are the application's numbers, not a model's: a model that could set its own weights could
set its own threshold, which workflows §11 forbids. They are chosen so that one critical finding
alone drops a unit below the default escalation threshold of 0.6 — a critical finding *should*
buy a deeper look — while a handful of nits does not."""


@dataclass(frozen=True, slots=True)
class AuditFinding:
    """One thing an audit noticed. It describes; it never prescribes text.

    Attributes:
        key: A stable identifier within the report, generated by IdeaPress.
        category: What kind of problem — the auditor's own word, recorded as data.
        severity: One of :data:`SEVERITY_ORDER`.
        problem_text: What is wrong.
        evidence_text: The passage it is about, quoted from the unit.
        required_fix_text: What would resolve it, **as a description**. Not replacement text: a
            repair stage reads this and writes; an auditor's words never become the unit.
        confidence: The auditor's own confidence, recorded and never acted on as a gate.
        uncertain: Whether the auditor flagged it as a guess.
        source_stage: Which stage produced it — ``audit_fast``, ``audit_deep``, ``fact_check``.
    """

    key: str
    category: str
    severity: Severity
    problem_text: str
    evidence_text: str = ""
    required_fix_text: str = ""
    confidence: float = 0.5
    uncertain: bool = False
    source_stage: str = "audit_fast"

    @property
    def weight(self) -> float:
        """What this finding costs the audit score."""
        return _SEVERITY_WEIGHT.get(self.severity, 0.15)


@dataclass(frozen=True, slots=True)
class AuditReport:
    """What an audit stage returns. **Findings only — there is no content field.**

    That absence is the mechanism behind "auditors report; the writer repairs", and it is asserted
    by a test rather than left to review.
    """

    findings: tuple[AuditFinding, ...]
    stage: str = "audit_fast"

    @property
    def score(self) -> float:
        """A quality score in ``[0, 1]``, computed from the findings by weight.

        Computed by Python from the findings' severities, **never taken from the model**. A model
        that scored its own output would be grading itself, which is the thing workflows §1 rule 2
        exists to prevent; a model that could weight the severities would be setting its own
        threshold, which workflows §11 forbids separately.
        """
        return max(0.0, 1.0 - sum(finding.weight for finding in self.findings))

    def by_severity(self, severity: Severity) -> tuple[AuditFinding, ...]:
        """Every finding of one severity."""
        return tuple(finding for finding in self.findings if finding.severity == severity)

    @property
    def worst(self) -> Severity | None:
        """The worst severity present, or ``None`` for a clean report."""
        for severity in SEVERITY_ORDER:
            if self.by_severity(severity):
                return severity
        return None

    def summary(self) -> str:
        """One line for a log or a CLI."""
        if not self.findings:
            return f"{self.stage}: no findings (score 1.00)"
        counts = ", ".join(
            f"{len(self.by_severity(s))} {s}" for s in SEVERITY_ORDER if self.by_severity(s)
        )
        return f"{self.stage}: {counts} (score {self.score:.2f})"


def weighted_score(findings: Sequence[AuditFinding]) -> float:
    """The audit score for a bare sequence of findings."""
    return AuditReport(findings=tuple(findings)).score


def finding_delta(before: Sequence[AuditFinding], after: Sequence[AuditFinding]) -> int:
    """How many findings a round removed. Negative when it added some.

    Deterministic, and the input to the diminishing-returns stop (workflows §5): improvement is
    "measured as the change in validation and audit findings between rounds — deterministic
    inputs, not the critic's self-assessment".
    """
    return len(before) - len(after)
