"""ideapress.domain.plan — the unit plan and the gate that decides whether it may stand.

Workflows §2 stage 4: *every blocking requirement assigned to ≥ 1 unit*. That is the whole gate,
and it is arithmetic — a set difference over identifiers Python generated. No model is asked
whether the plan looks complete, because a model saying "this plan covers everything" is precisely
the answer T1 exists to refuse.

The second gate is quieter and matters as much: **a plan with no units, or a compilation with no
requirements, does not pass.** A model that answers "looks good, no requirements needed" produces
an empty list, and an empty list trivially satisfies "every blocking requirement is assigned".
Vacuous truth is how a gate gets satisfied by saying nothing, so it is refused by name.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from baseaicore import ValidationError

if TYPE_CHECKING:
    from collections.abc import Sequence

    from ideapress.domain.requirements import Requirement

__all__ = ["Plan", "PlanUnit", "check_plan", "unit_key"]


def unit_key(ordinal: int) -> str:
    """The stable key for the *n*-th unit: ``U-01``, ``U-03``.

    Generated by IdeaPress, never taken from a model (risk S2): nothing a model produced becomes an
    identifier the system then trusts, or builds a path from.
    """
    return f"U-{ordinal:02d}"


@dataclass(frozen=True, slots=True)
class PlanUnit:
    """One unit of the plan: what it is for, and which requirements it carries.

    Attributes:
        key: ``U-01``. IdeaPress's, not the model's.
        ordinal: Position in the document, 1-based.
        title: The unit's heading.
        goal_text: What this unit must achieve, in a sentence.
        requirement_keys: Which compiled requirements this unit is responsible for.
        target_words: The length band's midpoint, when the plan states one.
    """

    key: str
    ordinal: int
    title: str
    goal_text: str
    requirement_keys: tuple[str, ...] = ()
    target_words: int | None = None


@dataclass(frozen=True, slots=True)
class Plan:
    """An ordered set of units, and the requirements they were planned against."""

    units: tuple[PlanUnit, ...]
    requirement_keys: tuple[str, ...]
    workflow_id: str = "standard"
    workflow_version: str = "1.0"

    def unit(self, key: str) -> PlanUnit:
        """Return the unit with this key.

        Raises:
            KeyError: No such unit.
        """
        for candidate in self.units:
            if candidate.key == key:
                return candidate
        raise KeyError(key)

    def units_for(self, requirement_key: str) -> tuple[PlanUnit, ...]:
        """Every unit carrying this requirement."""
        return tuple(unit for unit in self.units if requirement_key in unit.requirement_keys)


def check_plan(plan: Plan, requirements: Sequence[Requirement]) -> None:
    """Refuse a plan that does not carry every blocking requirement.

    Args:
        plan: The proposed unit plan.
        requirements: The compiled requirements it was planned against.

    Raises:
        ValidationError: Any of the four ways a plan can pass by saying nothing:

            * **no requirements were compiled at all.** "Every blocking requirement is assigned" is
              vacuously true of an empty set, so a compiler answering "looks good, no requirements
              needed" would otherwise satisfy this gate by producing nothing. Refused by name.
            * **the plan has no units.** Same shape, same refusal.
            * **a blocking requirement is assigned to no unit** — the gate workflows §2 states.
              The error **names every unmet requirement**, because a gate that fails without saying
              which requirement failed is a gate a person cannot act on.
            * **a unit cites a requirement that does not exist** — a key the model invented, which
              would otherwise look like coverage.

    Advisory requirements are deliberately **not** gated: workflows §3 says they inform critique
    only, and treating them as blocking "because it is stricter" is the trap risk-register entry
    T4 names — validators too strict, blocking legitimate content.
    """
    if not requirements:
        message = (
            "No requirements were compiled, so there is nothing for a plan to cover. A brief that "
            "genuinely states no constraints cannot be planned against; a compiler that returned "
            "an empty list for a brief that does state them has not done its job. Review the "
            "compilation before planning."
        )
        raise ValidationError(message, details={"requirement_count": 0})

    if not plan.units:
        message = (
            "The plan has no units, so no requirement can be assigned to one. An empty plan "
            "satisfies every coverage question by having nothing to check."
        )
        raise ValidationError(message, details={"unit_count": 0})

    known = {requirement.key for requirement in requirements}
    cited = {key for unit in plan.units for key in unit.requirement_keys}
    invented = sorted(cited - known)
    if invented:
        message = (
            f"The plan assigns {', '.join(invented)}, which no compiled requirement uses. A unit "
            "citing a requirement key that does not exist looks like coverage and is not."
        )
        raise ValidationError(message, details={"unknown_requirement_keys": invented})

    blocking = {requirement.key for requirement in requirements if requirement.blocking}
    unassigned = sorted(blocking - cited)
    if unassigned:
        by_key = {requirement.key: requirement for requirement in requirements}
        named = "; ".join(f"{key} ({by_key[key].text})" for key in unassigned)
        message = (
            f"{len(unassigned)} blocking requirement(s) are assigned to no unit: {named}. Every "
            "blocking requirement must be the responsibility of at least one unit, or nothing in "
            "the finished work is answerable for it."
        )
        raise ValidationError(
            message,
            details={
                "unassigned_requirement_keys": unassigned,
                "unassigned": [{"key": k, "text": by_key[k].text} for k in unassigned],
            },
        )
