"""plan tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-31 00:00:00.000000

Phase 3's five tables from data model §2: `requirements`, `units`, `stage_runs`, `attempts` and
`stage_events`. Autogenerated from the declarative models and then read: `weightsdb.PortableJSON`
and `weightsdb.UtcDateTime` are what make one migration correct on both SQLite and PostgreSQL, and
the PostgreSQL job runs this same file against a real server rather than trusting that it does.
"""

from __future__ import annotations

import sqlalchemy as sa
import weightsdb
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirements",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("requirement_key", sa.String(length=20), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("checks_json", weightsdb.PortableJSON(), nullable=False),
        sa.Column("source_document", sa.String(length=300), nullable=False),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("source_anchor", sa.String(length=200), nullable=True),
        sa.Column("compiled_by_prompt_id", sa.String(length=120), nullable=False),
        sa.Column("compiled_by_prompt_version", sa.String(length=20), nullable=False),
        sa.Column("compiled_by_prompt_sha256", sa.String(length=71), nullable=True),
        sa.Column("compiled_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
        sa.UniqueConstraint(
            "project_id", "generation", "requirement_key", name="uq_requirements_project_gen_key"
        ),
    )
    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.create_index(
            "ix_requirements_project_id_generation", ["project_id", "generation"], unique=False
        )

    op.create_table(
        "stage_runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("units_total", sa.Integer(), nullable=False),
        sa.Column("units_completed", sa.Integer(), nullable=False),
        sa.Column("units_paused", sa.Integer(), nullable=False),
        sa.Column("started_at", weightsdb.UtcDateTime(), nullable=False),
        sa.Column("completed_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("cancelled_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("options_json", weightsdb.PortableJSON(), nullable=False),
        sa.Column("backend", sa.String(length=40), nullable=False),
        sa.Column("backend_mode", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_stage_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_runs")),
    )
    with op.batch_alter_table("stage_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stage_runs_project_id_started_at", ["project_id", "started_at"], unique=False
        )

    op.create_table(
        "units",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("unit_key", sa.String(length=20), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("goal_text", sa.Text(), nullable=False),
        sa.Column("requirement_keys_json", weightsdb.PortableJSON(), nullable=False),
        sa.Column("target_words", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("current_version_id", sa.String(length=26), nullable=True),
        sa.Column("paused_reason", sa.Text(), nullable=True),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.Column("updated_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_units_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("project_id", "unit_key", name="uq_units_project_id_unit_key"),
    )
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.create_index(
            "ix_units_project_id_ordinal", ["project_id", "ordinal"], unique=False
        )

    op.create_table(
        "attempts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("stage_run_id", sa.String(length=26), nullable=False),
        sa.Column("unit_id", sa.String(length=26), nullable=True),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("backend", sa.String(length=40), nullable=False),
        sa.Column("backend_mode", sa.String(length=40), nullable=False),
        sa.Column("model_provider_kind", sa.String(length=40), nullable=True),
        sa.Column("model_provider_name", sa.String(length=200), nullable=True),
        sa.Column("model_digest", sa.String(length=71), nullable=True),
        sa.Column("model_canonical_id", sa.String(length=300), nullable=True),
        sa.Column("prompt_id", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("prompt_sha256", sa.String(length=71), nullable=True),
        sa.Column("rendered_prompt_sha256", sa.String(length=71), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("response_hash", sa.String(length=71), nullable=True),
        sa.Column("structured_output_json", weightsdb.PortableJSON(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("thinking_tokens", sa.Integer(), nullable=True),
        sa.Column("provider_ms", sa.Float(), nullable=True),
        sa.Column("overhead_ms", sa.Float(), nullable=True),
        sa.Column("ttft_ms", sa.Float(), nullable=True),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("routing_json", weightsdb.PortableJSON(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=60), nullable=True),
        sa.Column("degradations_json", weightsdb.PortableJSON(), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_run_id"],
            ["stage_runs.id"],
            name=op.f("fk_attempts_stage_run_id_stage_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
        sa.UniqueConstraint(
            "stage_run_id",
            "unit_id",
            "stage",
            "attempt",
            "round",
            name="uq_attempts_run_unit_stage_attempt_round",
        ),
    )
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attempts_stage_run_id_unit_id_stage",
            ["stage_run_id", "unit_id", "stage"],
            unique=False,
        )

    op.create_table(
        "stage_events",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("stage_run_id", sa.String(length=26), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("timestamp", weightsdb.UtcDateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("unit_id", sa.String(length=26), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data_json", weightsdb.PortableJSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_run_id"],
            ["stage_runs.id"],
            name=op.f("fk_stage_events_stage_run_id_stage_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_events")),
        sa.UniqueConstraint("stage_run_id", "sequence", name="uq_stage_events_run_sequence"),
    )
    with op.batch_alter_table("stage_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stage_events_stage_run_id_sequence", ["stage_run_id", "sequence"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stage_events", schema=None) as batch_op:
        batch_op.drop_index("ix_stage_events_stage_run_id_sequence")

    op.drop_table("stage_events")
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_attempts_stage_run_id_unit_id_stage")

    op.drop_table("attempts")
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.drop_index("ix_units_project_id_ordinal")

    op.drop_table("units")
    with op.batch_alter_table("stage_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_stage_runs_project_id_started_at")

    op.drop_table("stage_runs")
    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.drop_index("ix_requirements_project_id_generation")

    op.drop_table("requirements")
    # ### end Alembic commands ###
