"""unit versions

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-31 00:00:00.000000

Phase 4's four tables from data model §2: `unit_versions`, `validations`, `coverage` and `exports`.
Autogenerated from the declarative models and then read; the parity check compares both back.
"""

from __future__ import annotations

import sqlalchemy as sa
import weightsdb
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exports",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=71), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("unit_version_ids_json", weightsdb.PortableJSON(), nullable=False),
        sa.Column("export_format_version", sa.String(length=20), nullable=False),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_exports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
    )
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_exports_project_id_created_at", ["project_id", "created_at"], unique=False
        )

    op.create_table(
        "unit_versions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("unit_id", sa.String(length=26), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("committed", sa.Boolean(), nullable=False),
        sa.Column("committed_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("created_from_attempt_id", sa.String(length=26), nullable=True),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_unit_versions_unit_id_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_versions")),
        sa.UniqueConstraint("unit_id", "version", name="uq_unit_versions_unit_id_version"),
    )
    with op.batch_alter_table("unit_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_unit_versions_unit_id_version", ["unit_id", "version"], unique=False
        )

    op.create_table(
        "coverage",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("unit_version_id", sa.String(length=26), nullable=False),
        sa.Column("requirement_id", sa.String(length=26), nullable=False),
        sa.Column("satisfied", sa.Boolean(), nullable=False),
        sa.Column("satisfied_by", sa.String(length=30), nullable=False),
        sa.Column("detail_json", weightsdb.PortableJSON(), nullable=False),
        sa.Column("evaluated_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_coverage_requirement_id_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_version_id"],
            ["unit_versions.id"],
            name=op.f("fk_coverage_unit_version_id_unit_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage")),
        sa.UniqueConstraint(
            "unit_version_id", "requirement_id", name="uq_coverage_version_requirement"
        ),
    )
    with op.batch_alter_table("coverage", schema=None) as batch_op:
        batch_op.create_index(
            "ix_coverage_unit_version_id_requirement_id",
            ["unit_version_id", "requirement_id"],
            unique=False,
        )

    op.create_table(
        "validations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("attempt_id", sa.String(length=26), nullable=False),
        sa.Column("check_kind", sa.String(length=40), nullable=False),
        sa.Column("check_key", sa.String(length=120), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("detail_json", weightsdb.PortableJSON(), nullable=False),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_validations_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validations")),
    )
    with op.batch_alter_table("validations", schema=None) as batch_op:
        batch_op.create_index("ix_validations_attempt_id", ["attempt_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("validations", schema=None) as batch_op:
        batch_op.drop_index("ix_validations_attempt_id")

    op.drop_table("validations")
    with op.batch_alter_table("coverage", schema=None) as batch_op:
        batch_op.drop_index("ix_coverage_unit_version_id_requirement_id")

    op.drop_table("coverage")
    with op.batch_alter_table("unit_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_unit_versions_unit_id_version")

    op.drop_table("unit_versions")
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.drop_index("ix_exports_project_id_created_at")

    op.drop_table("exports")
    # ### end Alembic commands ###
