"""review tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-31 00:00:00.000000

Phase 5's two tables from data model §2: `audit_findings` and `critiques`. Neither carries unit
content — an auditor reports and a critic judges; the writer stage is the only one that writes.
"""

from __future__ import annotations

import sqlalchemy as sa
import weightsdb
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_findings",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("attempt_id", sa.String(length=26), nullable=False),
        sa.Column("finding_key", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("problem_text", sa.Text(), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("target_ref", sa.String(length=120), nullable=True),
        sa.Column("required_fix_text", sa.Text(), nullable=True),
        sa.Column("uncertain", sa.Boolean(), nullable=False),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("source_stage", sa.String(length=30), nullable=False),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_audit_findings_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_findings")),
    )
    with op.batch_alter_table("audit_findings", schema=None) as batch_op:
        batch_op.create_index("ix_audit_findings_attempt_id", ["attempt_id"], unique=False)

    op.create_table(
        "critiques",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("attempt_id", sa.String(length=26), nullable=False),
        sa.Column("verdict", sa.String(length=30), nullable=False),
        sa.Column("rationale_text", sa.Text(), nullable=False),
        sa.Column("improvement_delta", sa.Float(), nullable=True),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("stop_reason", sa.String(length=40), nullable=True),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_critiques_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_critiques")),
    )
    with op.batch_alter_table("critiques", schema=None) as batch_op:
        batch_op.create_index("ix_critiques_attempt_id", ["attempt_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("critiques", schema=None) as batch_op:
        batch_op.drop_index("ix_critiques_attempt_id")

    op.drop_table("critiques")
    with op.batch_alter_table("audit_findings", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_findings_attempt_id")

    op.drop_table("audit_findings")
    # ### end Alembic commands ###
