"""stage run ownership

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-31 00:00:00.000000

Which process owns a stage run. Without it, `mark_interrupted` — which runs whenever a Runtime is
built — marks every row still `running` as dead, including one a *live* process is executing. The
M7 demonstration found this the hard way: a read-only inspection from a second process killed the
state of a draft that was three units in.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stage_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_pid", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("owner_boot_id", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stage_runs", schema=None) as batch_op:
        batch_op.drop_column("owner_boot_id")
        batch_op.drop_column("owner_pid")

    # ### end Alembic commands ###
