"""LoadLedger's mounted tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-07 00:00:00.000000

Row J1 (IP-A1), and the **first package-table mount in this application** (ADR-0050). What that
pattern asks of a host is exactly this file plus the one unconditional
``mount_ledger_tables(Base.metadata)`` call at the bottom of ``ideapress.infrastructure.db.models``:
the package ships table *shapes* and never a migration history, so its four tables appear in
IdeaPress's own autogenerate diff, upgrade with IdeaPress's own history, and are backed up, restored
and pruned by whoever owns this database. Commissioner's ``egress_decisions`` mount at ``0008``
copies this shape, and both transcribe PromptCadence's ``0005``/``0006`` — the suite's first host of
this pattern — rather than inventing a second design.

Three details are contract rather than style, and a later mount must keep all three:

* **The prefix is the package's default** (``ledger_``). It is part of the mounted contract:
  changing it once a deployment has migrated is a table rename, not a configuration change.
* **The DDL below is autogenerated against the mount, not transcribed from the package.** The
  parity test (``check_parity`` over ``Base.metadata``) is what proves the two agree, on both
  dialects, and it is the reason nothing here may be hand-tuned.
* **Every accumulating integer is a BigInteger.** That is LoadLedger's own rule: :class:`baseaicore.
  Money` is whole *nanos*, so a modest few-dollar ceiling is already past a 4-byte integer's
  2 147 483 647.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    op.create_table(
        "ledger_entries",
        sa.Column("entry_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("source_ref", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unpriced", sa.Boolean(), nullable=False),
        sa.Column("pricing_hash", sa.String(), nullable=True),
        sa.Column("debit_json", sa.Text(), nullable=False),
        sa.Column("verdicts_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("entry_id", name="pk_ledger_entries"),
    )
    op.create_index("ix_ledger_entries_occurred_at", "ledger_entries", ["occurred_at"])
    op.create_index("ix_ledger_entries_run", "ledger_entries", ["run_id", "entry_id"])
    op.create_table(
        "ledger_balances",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("window_key", sa.String(), nullable=False),
        sa.Column("tokens_spent", sa.BigInteger(), nullable=False),
        sa.Column("unpriced_debit_count", sa.BigInteger(), nullable=False),
        sa.Column("untotalled_debit_count", sa.BigInteger(), nullable=False),
        sa.Column("unmetered_debit_count", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("scope", "window_key", name="pk_ledger_balances"),
    )
    op.create_table(
        "ledger_balance_money",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("window_key", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("nanos_spent", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("scope", "window_key", "currency", name="pk_ledger_balance_money"),
    )
    op.create_table(
        "ledger_runs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("declared_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("run_id", name="pk_ledger_runs"),
    )


def downgrade() -> None:
    op.drop_table("ledger_runs")
    op.drop_table("ledger_balance_money")
    op.drop_table("ledger_balances")
    op.drop_index("ix_ledger_entries_run", table_name="ledger_entries")
    op.drop_index("ix_ledger_entries_occurred_at", table_name="ledger_entries")
    op.drop_table("ledger_entries")
