"""A shipped 1.0 configuration file still loads to a 1.0 settings object.

Gate C's guard, and the exit condition that is asserted rather than argued. 1.1 adds two keys —
`[models.stage_adapters]` and `[inference] data_classification` — and neither may move an existing
value, change an existing default, or make an existing file mean something new.

The golden was produced by **`v1.0.0`'s own code**, not by this build: a worktree at the tag loaded
its own `EXAMPLE_CONFIG_TOML` and dumped the result. A golden generated by the version under test
would agree with any change either of them made together.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from ideapress.config import load_settings

GOLDENS = Path(__file__).parent / "goldens"
EXAMPLE_1_0 = GOLDENS / "config_1_0_example.toml"
SETTINGS_1_0 = GOLDENS / "settings_1_0_0.json"

ADDED_IN_1_1: dict[str, set[str]] = {
    "inference": {"data_classification"},
    "models": {"stage_adapters"},
}

# Row J1 (staged for 1.2.0, unreleased — ground truth 1 of its kickoff): two whole new sections
# that exist only to carry LoadLedger's and Commissioner's own configuration, plus one new leaf key
# on each of the two backends that can be remote. None moves an existing value or default.
ADDED_IN_J1_SECTIONS: set[str] = {"budget", "pricing"}
ADDED_IN_J1_NESTED: dict[str, set[str]] = {
    "loadcoach": {"max_data_classification"},
    "openai_compatible": {"max_data_classification"},
}

# Row K3 (staged for 1.2.0, unreleased): project_review's whole-document context gets its own
# budget key, alongside the per-unit `context_budget_tokens` it already had.
ADDED_IN_K3: dict[str, set[str]] = {
    "workflow": {"project_review_context_budget_tokens"},
}


# Row M1 (staged for 1.4.0): the `research` stage's whole configuration, a new section with every
# default closed — no host, so a 1.0 file that never mentioned it fetches nothing.
ADDED_IN_M1_SECTIONS: set[str] = {"research"}
ADDED_IN_WM2_SECTIONS: set[str] = {"console"}
"""Row WM2: `[console] url`, WeightRoomGym's address for the top-bar tab strip."""

ADDED_IN_WPF7_NESTED: dict[str, set[str]] = {
    "ollama": {"served_context_tokens"},
}
"""Row WPF7: the context IdeaPress asks Ollama to serve, and checks its budgets against. New, and
it moves no existing value: 0 means what every build before it did, the server's own default."""


def _without_1_1_keys(dump: dict[str, Any]) -> dict[str, Any]:
    """Return ``dump`` with exactly the keys 1.1, rows J1, K3, M1 and WM2 added removed, and
    nothing else."""
    trimmed = {section: dict(values) for section, values in dump.items()}
    for section, keys in {**ADDED_IN_1_1, **ADDED_IN_K3}.items():
        for key in keys:
            assert key in trimmed[section], f"{section}.{key} is missing from the 1.1 dump"
            del trimmed[section][key]
    for section in ADDED_IN_J1_SECTIONS | ADDED_IN_M1_SECTIONS | ADDED_IN_WM2_SECTIONS:
        assert section in trimmed, f"{section} is missing from the dump"
        del trimmed[section]
    for backend, keys in {**ADDED_IN_J1_NESTED, **ADDED_IN_WPF7_NESTED}.items():
        for key in keys:
            assert key in trimmed["inference"][backend], f"inference.{backend}.{key} is missing"
            del trimmed["inference"][backend][key]
    return trimmed


@pytest.fixture
def _pinned_paths(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin the XDG lookups the golden was generated under, so paths are not machine-dependent."""
    monkeypatch.setenv("IDEAPRESS_DATA_DIR", "/golden/data")
    monkeypatch.setenv("XDG_CONFIG_HOME", "/golden/config")


@pytest.mark.usefixtures("_pinned_paths")
def test_the_shipped_1_0_configuration_loads_to_a_1_0_settings_object(tmp_path: Path) -> None:
    """Byte-for-byte, once the two keys 1.1 added are taken back out."""
    config = tmp_path / "ideapress.toml"
    config.write_text(EXAMPLE_1_0.read_text(encoding="utf-8"), encoding="utf-8")

    loaded = load_settings(config_path=config)
    dump = loaded.settings.model_dump(mode="json")

    expected = json.loads(SETTINGS_1_0.read_text(encoding="utf-8"))
    assert _without_1_1_keys(dump) == expected


@pytest.mark.usefixtures("_pinned_paths")
def test_the_new_keys_default_to_no_behaviour_at_all(tmp_path: Path) -> None:
    """No pins, and the lowest classification — so the join equals the adapter's own value."""
    config = tmp_path / "ideapress.toml"
    config.write_text(EXAMPLE_1_0.read_text(encoding="utf-8"), encoding="utf-8")

    settings = load_settings(config_path=config).settings

    assert settings.models.stage_adapters == {}
    assert settings.inference.data_classification == "public"
    # Row M1: no host named, so `http_fetch` is never registered and the workflow is 1.0's.
    assert settings.research.allowed_hosts == ()
    assert settings.research.max_data_classification is None
